### ISSUE TITLE
Add test-simple to Stackage.

### ISSUE THREAD

**Issue by jship** [bosu/test-simple#1]
It would be helpful if test-simple was available on Stackage. This looks to be a prerequisite for getting hscope on Stackage.

Note that QuickCheck's upper bound would need to be bumped to be compatible with LTS 4.1.

Are you interested in this? I can set up Stackage's build-constraints.yml if you'd like.

**Comment by bosu** [comment]
Yes, I am interested and will happily merge.

Thanks,
Boris.

**Comment by jship** [comment]
I submitted PR (#2) to move test-simple along towards being Stackage-ready.  Please see that PR for details.

If this PR is merged in, a new version of test-simple will have to be uploaded to Hackage.

**Comment by bosu** [comment]
Merged and uploaded, thanks!
